conditioning:
  method: mala
  params:
    scale: 0.2
    multiplier: 0.36
  initializer:
    method: lgd
    params:
      scale: 500.0
      lambda: 0.00002

data:
  name: general
  root: ./data/ffhq
  # Uncomment the following and change the root therein to initialize with given images (e.g. outputs of LGD-MC)
  # init_config:
  #   name: general
  #   root: ./results/quantization/recon/

measurement:
  operator:
    name: quantization
    dither_name: logit
    intensity: 0.4

  noise: 
    name: gaussian
    sigma: 0.0

