conditioning:
  method: lgd
  params:
    scale: 30.0
    lambda: 0.001

data:
  name: general
  root: ./data/ffhq

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.2
