conditioning:
  method: mala
  params:
    scale: 0.6
  initializer:
    method: lgd
    params:
      scale: 30.0
      lambda: 0.001

data:
  name: general
  root: ./data/ffhq
  # Uncomment the following and change the root therein to initialize with given images (e.g. outputs of LGD-MC)
  # init_config:
  #   name: general
  #   root: ./results/super_resolution/recon/
  

measurement:
  operator:
    name: super_resolution
    in_shape: !!python/tuple [1, 3, 256, 256]
    scale_factor: 4
  
  noise: 
    name: gaussian
    sigma: 0.2
